app/Http/routes.php
<?php

Route::group(['middleware' => 'web'], function () {
    /**
     * Switch between the included languages
     */
    Route::group(['namespace' => 'Language'], function () {
        require(__DIR__ . '/Routes/Language/Language.php');
    });

    /**
     * Frontend Routes
     * Namespaces indicate folder structure
     */
//    Route::resource('posts', 'PostController');

    Route::group(['namespace' => 'Frontend'], function () {
        require(__DIR__ . '/Routes/Frontend/Frontend.php');
        require(__DIR__ . '/Routes/Frontend/Access.php');


    });
});


/**
 * Backend Routes
 * Namespaces indicate folder structure
 * Admin middleware groups web, auth, and routeNeedsPermission
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    /**
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    require(__DIR__ . '/Routes/Backend/Dashboard.php');
    require(__DIR__ . '/Routes/Backend/Access.php');
    require(__DIR__ . '/Routes/Backend/LogViewer.php');
});


/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
        require config('infyom.laravel_generator.path.api_routes');
    });
});


Route::group(['middleware' => 'admin'], function () {
    

    Route::get('admin/banners', ['as' => 'admin.banners.index', 'uses' => 'Admin\BannerController@index']);
    Route::post('admin/banners', ['as' => 'admin.banners.store', 'uses' => 'Admin\BannerController@store']);
    Route::get('admin/banners/create', ['as' => 'admin.banners.create', 'uses' => 'Admin\BannerController@create']);
    Route::put('admin/banners/{banners}', ['as' => 'admin.banners.update', 'uses' => 'Admin\BannerController@update']);
    Route::patch('admin/banners/{banners}', ['as' => 'admin.banners.update', 'uses' => 'Admin\BannerController@update']);
    Route::delete('admin/banners/{banners}', ['as' => 'admin.banners.destroy', 'uses' => 'Admin\BannerController@destroy']);
    Route::get('admin/banners/{banners}', ['as' => 'admin.banners.show', 'uses' => 'Admin\BannerController@show']);
    Route::get('admin/banners/{banners}/edit', ['as' => 'admin.banners.edit', 'uses' => 'Admin\BannerController@edit']);


    Route::get('admin/pages', ['as' => 'admin.pages.index', 'uses' => 'Admin\PageController@index']);
    Route::post('admin/pages', ['as' => 'admin.pages.store', 'uses' => 'Admin\PageController@store']);
    Route::get('admin/pages/create', ['as' => 'admin.pages.create', 'uses' => 'Admin\PageController@create']);
    Route::put('admin/pages/{pages}', ['as' => 'admin.pages.update', 'uses' => 'Admin\PageController@update']);
    Route::patch('admin/pages/{pages}', ['as' => 'admin.pages.update', 'uses' => 'Admin\PageController@update']);
    Route::delete('admin/pages/{pages}', ['as' => 'admin.pages.destroy', 'uses' => 'Admin\PageController@destroy']);
    Route::get('admin/pages/{pages}', ['as' => 'admin.pages.show', 'uses' => 'Admin\PageController@show']);
    Route::get('admin/pages/{pages}/edit', ['as' => 'admin.pages.edit', 'uses' => 'Admin\PageController@edit']);


    Route::get('admin/locations', ['as'=> 'admin.locations.index', 'uses' => 'Admin\LocationController@index']);
    Route::post('admin/locations', ['as'=> 'admin.locations.store', 'uses' => 'Admin\LocationController@store']);
    Route::get('admin/locations/create', ['as'=> 'admin.locations.create', 'uses' => 'Admin\LocationController@create']);
    Route::put('admin/locations/{locations}', ['as'=> 'admin.locations.update', 'uses' => 'Admin\LocationController@update']);
    Route::patch('admin/locations/{locations}', ['as'=> 'admin.locations.update', 'uses' => 'Admin\LocationController@update']);
    Route::delete('admin/locations/{locations}', ['as'=> 'admin.locations.destroy', 'uses' => 'Admin\LocationController@destroy']);
    Route::get('admin/locations/{locations}', ['as'=> 'admin.locations.show', 'uses' => 'Admin\LocationController@show']);
    Route::get('admin/locations/{locations}/edit', ['as'=> 'admin.locations.edit', 'uses' => 'Admin\LocationController@edit']);



    Route::get('admin/news', ['as'=> 'admin.news.index', 'uses' => 'Admin\NewsController@index']);
    Route::post('admin/news', ['as'=> 'admin.news.store', 'uses' => 'Admin\NewsController@store']);
    Route::get('admin/news/create', ['as'=> 'admin.news.create', 'uses' => 'Admin\NewsController@create']);
    Route::put('admin/news/{news}', ['as'=> 'admin.news.update', 'uses' => 'Admin\NewsController@update']);
    Route::patch('admin/news/{news}', ['as'=> 'admin.news.update', 'uses' => 'Admin\NewsController@update']);
    Route::delete('admin/news/{news}', ['as'=> 'admin.news.destroy', 'uses' => 'Admin\NewsController@destroy']);
    Route::get('admin/news/{news}', ['as'=> 'admin.news.show', 'uses' => 'Admin\NewsController@show']);
    Route::get('admin/news/{news}/edit', ['as'=> 'admin.news.edit', 'uses' => 'Admin\NewsController@edit']);

    

    Route::get('admin/maps', ['as'=> 'admin.maps.index', 'uses' => 'Admin\MapController@index']);
    Route::post('admin/maps', ['as'=> 'admin.maps.store', 'uses' => 'Admin\MapController@store']);
    Route::get('admin/maps/create', ['as'=> 'admin.maps.create', 'uses' => 'Admin\MapController@create']);
    Route::put('admin/maps/{maps}', ['as'=> 'admin.maps.update', 'uses' => 'Admin\MapController@update']);
    Route::patch('admin/maps/{maps}', ['as'=> 'admin.maps.update', 'uses' => 'Admin\MapController@update']);
    Route::delete('admin/maps/{maps}', ['as'=> 'admin.maps.destroy', 'uses' => 'Admin\MapController@destroy']);
    Route::get('admin/maps/{maps}', ['as'=> 'admin.maps.show', 'uses' => 'Admin\MapController@show']);
    Route::get('admin/maps/{maps}/edit', ['as'=> 'admin.maps.edit', 'uses' => 'Admin\MapController@edit']);
    

    Route::get('admin/galleries', ['as'=> 'admin.galleries.index', 'uses' => 'Admin\GalleryController@index']);
    Route::post('admin/galleries', ['as'=> 'admin.galleries.store', 'uses' => 'Admin\GalleryController@store']);
    Route::get('admin/galleries/create', ['as'=> 'admin.galleries.create', 'uses' => 'Admin\GalleryController@create']);
    Route::put('admin/galleries/{galleries}', ['as'=> 'admin.galleries.update', 'uses' => 'Admin\GalleryController@update']);
    Route::patch('admin/galleries/{galleries}', ['as'=> 'admin.galleries.update', 'uses' => 'Admin\GalleryController@update']);
    Route::delete('admin/galleries/{galleries}', ['as'=> 'admin.galleries.destroy', 'uses' => 'Admin\GalleryController@destroy']);
    Route::get('admin/galleries/{galleries}', ['as'=> 'admin.galleries.show', 'uses' => 'Admin\GalleryController@show']);
    Route::get('admin/galleries/{galleries}/edit', ['as'=> 'admin.galleries.edit', 'uses' => 'Admin\GalleryController@edit']);

    

    Route::get('admin/contacts', ['as'=> 'admin.contacts.index', 'uses' => 'Admin\ContactController@index']);
    Route::post('admin/contacts', ['as'=> 'admin.contacts.store', 'uses' => 'Admin\ContactController@store']);
    Route::get('admin/contacts/create', ['as'=> 'admin.contacts.create', 'uses' => 'Admin\ContactController@create']);
    Route::put('admin/contacts/{contacts}', ['as'=> 'admin.contacts.update', 'uses' => 'Admin\ContactController@update']);
    Route::patch('admin/contacts/{contacts}', ['as'=> 'admin.contacts.update', 'uses' => 'Admin\ContactController@update']);
    Route::delete('admin/contacts/{contacts}', ['as'=> 'admin.contacts.destroy', 'uses' => 'Admin\ContactController@destroy']);
    Route::get('admin/contacts/{contacts}', ['as'=> 'admin.contacts.show', 'uses' => 'Admin\ContactController@show']);
    Route::get('admin/contacts/{contacts}/edit', ['as'=> 'admin.contacts.edit', 'uses' => 'Admin\ContactController@edit']);




    Route::get('admin/subCategories', ['as'=> 'admin.subCategories.index', 'uses' => 'Admin\SubCategoryController@index']);
    Route::post('admin/subCategories', ['as'=> 'admin.subCategories.store', 'uses' => 'Admin\SubCategoryController@store']);
    Route::get('admin/subCategories/create', ['as'=> 'admin.subCategories.create', 'uses' => 'Admin\SubCategoryController@create']);
    Route::put('admin/subCategories/{subCategories}', ['as'=> 'admin.subCategories.update', 'uses' => 'Admin\SubCategoryController@update']);
    Route::patch('admin/subCategories/{subCategories}', ['as'=> 'admin.subCategories.update', 'uses' => 'Admin\SubCategoryController@update']);
    Route::delete('admin/subCategories/{subCategories}', ['as'=> 'admin.subCategories.destroy', 'uses' => 'Admin\SubCategoryController@destroy']);
    Route::get('admin/subCategories/{subCategories}', ['as'=> 'admin.subCategories.show', 'uses' => 'Admin\SubCategoryController@show']);
    Route::get('admin/subCategories/{subCategories}/edit', ['as'=> 'admin.subCategories.edit', 'uses' => 'Admin\SubCategoryController@edit']);



    Route::get('admin/books', ['as'=> 'admin.books.index', 'uses' => 'Admin\BookController@index']);
    Route::post('admin/books', ['as'=> 'admin.books.store', 'uses' => 'Admin\BookController@store']);
    Route::get('admin/books/create', ['as'=> 'admin.books.create', 'uses' => 'Admin\BookController@create']);
    Route::put('admin/books/{books}', ['as'=> 'admin.books.update', 'uses' => 'Admin\BookController@update']);
    Route::patch('admin/books/{books}', ['as'=> 'admin.books.update', 'uses' => 'Admin\BookController@update']);
    Route::delete('admin/books/{books}', ['as'=> 'admin.books.destroy', 'uses' => 'Admin\BookController@destroy']);

app/Models/Access/Permission/Permission.php
<?php

namespace App\Models\Access\Permission;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Permission\Traits\Relationship\PermissionRelationship;

/**
 * Class Permission
 * @package App\Models\Access\Permission
 */
class Permission extends Model
{
    use PermissionRelationship;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'display_name', 'sort'];

    /**
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->table = config('access.permissions_table');
    }
}

app/Models/Access/User/Traits/Attribute/UserAttribute.php
<?php

namespace App\Models\Access\User\Traits\Attribute;

/**
 * Class UserAttribute
 * @package App\Models\Access\User\Traits\Attribute
 */
trait UserAttribute
{

    /**
     * @return mixed
     */
    public function canChangeEmail()
    {
        return config('access.users.change_email');
    }

    /**
     * @return bool
     */
    public function canChangePassword()
    {
        return ! app('session')->has(config('access.socialite_session_name'));
    }

    /**
     * @return string
     */
    public function getConfirmedLabelAttribute()
    {
        if ($this->isConfirmed())
            return "<label class='label label-success'>".trans('labels.general.yes')."</label>";
        return "<label class='label label-danger'>".trans('labels.general.no')."</label>";
    }

    /**
     * @return mixed
     */
    public function getPictureAttribute()
    {
        return $this->getPicture();
    }

    /**
     * @param bool $size
     * @return mixed
     */
    public function getPicture($size = false)
    {
        if (! $size) $size = config('gravatar.default.size');
        return gravatar()->get($this->email, ['size' => $size]);
    }

    /**
     * @param $provider
     * @return bool
     */
    public function hasProvider($provider)
    {
        foreach ($this->providers as $p) {
            if ($p->provider == $provider) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return bool
     */
    public function isActive() {
        return $this->status == 1;
    }

    /**
     * @return bool
     */
    public function isConfirmed() {
        return $this->confirmed == 1;
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute()
    {
        return '<a href="' . route('admin.access.user.edit', $this) . '" class="btn btn-xs btn-primary"><i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.edit') . '"></i></a> ';
    }

    /**
     * @return string
     */
    public function getChangePasswordButtonAttribute()
    {
        return '<a href="' . route('admin.access.user.change-password', $this) . '" class="btn btn-xs btn-info"><i class="fa fa-refresh" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.backend.access.users.change_password') . '"></i></a> ';
    }

    /**
     * @return string
     */
    public function getStatusButtonAttribute()
    {
        if ($this->id != access()->id()) {
            switch ($this->status) {
                case 0:
                    return '<a href="' . route('admin.access.user.mark', [
                        $this,
                        1
                    ]) . '" class="btn btn-xs btn-success"><i class="fa fa-play" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.backend.access.users.activate') . '"></i></a> ';
                // No break

                case 1:
                    return '<a href="' . route('admin.access.user.mark', [
                        $this,
                        0
                    ]) . '" class="btn btn-xs btn-warning"><i class="fa fa-pause" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.backend.access.users.deactivate') . '"></i></a> ';
                // No break

                default:
                    return '';
                // No break
            }
        }

        return '';
    }

    /**
     * @return string
     */
    public function getConfirmedButtonAttribute()
    {
        if (! $this->isConfirmed()) {
            return '<a href="' . route('admin.account.confirm.resend', $this) . '" class="btn btn-xs btn-success"><i class="fa fa-refresh" data-toggle="tooltip" data-placement="top" title=' . trans('buttons.backend.access.users.resend_email') . '"></i></a> ';
        }

        return '';
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute()
    {
        if ($this->id != access()->id()) {
            return '<a href="' . route('admin.access.user.destroy', $this) . '"
                 data-method="delete"
                 data-trans-button-cancel="' . trans('buttons.general.cancel') . '"
                 data-trans-button-confirm="' . trans('buttons.general.crud.delete') . '"
                 data-trans-title="' . trans('strings.backend.general.are_you_sure') . '"
                 class="btn btn-xs btn-danger"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.general.crud.delete') . '"></i></a> ';
        }

        return '';
    }

	/**
     * @return string
     */
    public function getRestoreButtonAttribute()
    {
        return '<a href="' . route('admin.access.user.restore', $this) . '" name="restore_user" class="btn btn-xs btn-info"><i class="fa fa-refresh" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.backend.access.users.restore_user') . '"></i></a> ';
    }

	/**
     * @return string
     */
    public function getDeletePermanentlyButtonAttribute()
    {
        return '<a href="' . route('admin.access.user.delete-permanently', $this) . '" name="delete_user_perm" class="btn btn-xs btn-danger"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.backend.access.users.delete_permanently') . '"></i></a> ';
    }

	/**
     * @return string
     */
    public function getLoginAsButtonAttribute()
    {
        /**
         * If the admin is currently NOT spoofing a user
         */
        if (! session()->has("admin_user_id") || ! session()->has("temp_user_id")) {
            //Won't break, but don't let them "Login As" themselves
            if ($this->id != access()->id()) {
                return '<a href="' . route('admin.access.user.login-as',
                    $this) . '" class="btn btn-xs btn-success"><i class="fa fa-lock" data-toggle="tooltip" data-placement="top" title="' . trans('buttons.backend.access.users.login_as',
                    ['user' => $this->name]) . '"></i></a> ';
            }
        }

        return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        if ($this->deleted_at) {
            return $this->getRestoreButtonAttribute() .
                $this->getDeletePermanentlyButtonAttribute();
        }

        return
            $this->getLoginAsButtonAttribute() .
            $this->getEditButtonAttribute() .
            $this->getChangePasswordButtonAttribute() .
            $this->getStatusButtonAttribute() .
            $this->getConfirmedButtonAttribute() .
            $this->getDeleteButtonAttribute();
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

/**
 * Class DashboardController
 * @package App\Http\Controllers\Backend
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard');
    }
}

resources/views/backend/access/create.blade.php
@extends ('backend.layouts.master')

@section ('title', trans('labels.backend.access.users.management') . ' | ' . trans('labels.backend.access.users.create'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.access.users.management') }}
        <small>{{ trans('labels.backend.access.users.create') }}</small>
    </h1>
@endsection

@section('content')
    {{ Form::open(['route' => 'admin.access.user.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post','files'=>true]) }}

        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">{{ trans('labels.backend.access.users.create') }}</h3>

                <div class="box-tools pull-right">
                    @include('backend.access.includes.partials.header-buttons')
                </div><!--box-tools pull-right-->
            </div><!-- /.box-header -->

            <div class="box-body">
                <div class="form-group">
                    {{ Form::label('name', trans('validation.attributes.backend.access.users.name'), ['class' => 'col-lg-2 control-label']) }}

                    <div class="col-lg-10">
                        {{ Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('validation.attributes.backend.access.users.name')]) }}
                    </div><!--col-lg-10-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('email', trans('validation.attributes.backend.access.users.email'), ['class' => 'col-lg-2 control-label']) }}

                    <div class="col-lg-10">
                        {{ Form::text('email', null, ['class' => 'form-control', 'placeholder' => trans('validation.attributes.backend.access.users.email')]) }}
                    </div><!--col-lg-10-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('password', trans('validation.attributes.backend.access.users.password'), ['class' => 'col-lg-2 control-label', 'placeholder' => trans('validation.attributes.backend.access.users.password')]) }}

                    <div class="col-lg-10">
                        {{ Form::password('password', ['class' => 'form-control']) }}
                    </div><!--col-lg-10-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('password_confirmation', trans('validation.attributes.backend.access.users.password_confirmation'), ['class' => 'col-lg-2 control-label', 'placeholder' => trans('validation.attributes.backend.access.users.password_confirmation')]) }}

                    <div class="col-lg-10">
                        {{ Form::password('password_confirmation', ['class' => 'form-control']) }}
                    </div><!--col-lg-10-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('status', trans('validation.attributes.backend.access.users.active'), ['class' => 'col-lg-2 control-label']) }}

                    <div class="col-lg-1">
                        {{ Form::checkbox('status', '1', true) }}
                    </div><!--col-lg-1-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('confirmed', trans('validation.attributes.backend.access.users.confirmed'), ['class' => 'col-lg-2 control-label']) }}

                    <div class="col-lg-1">
                        {{ Form::checkbox('confirmed', '1', true) }}
                    </div><!--col-lg-1-->
                </div><!--form control-->


                {{--<div class="form-group">--}}
                    {{--<label class ='col-lg-2 control-label'>Image Logo </label>--}}

                    {{--<div class="col-lg-10">--}}
                        {{--{{Form::file('image')}}--}}
                    {{--</div><!--col-lg-1-->--}}
                {{--</div><!--form control-->--}}


                <div class="form-group">
                    <label class="col-lg-2 control-label">{{ trans('validation.attributes.backend.access.users.send_confirmation_email') }}<br/>
                        <small>{{ trans('strings.backend.access.users.if_confirmed_off') }}</small>
                    </label>

                    <div class="col-lg-1">
                        {{ Form::checkbox('confirmation_email', '1') }}
                    </div><!--col-lg-1-->
                </div><!--form control-->

                <div class="form-group">
                    {{ Form::label('status', trans('validation.attributes.backend.access.users.associated_roles'), ['class' => 'col-lg-2 control-label']) }}

                    <div class="col-lg-3">
                        @if (count($roles) > 0)
                            @foreach($roles as $role)
                                <input type="checkbox" value="{{ $role->id }}" name="assignees_roles[]" id="role-{{ $role->id }}" /> <label for="role-{{ $role->id }}">{{ $role->name }}</label>
                                <a href="#" data-role="role_{{ $role->id }}" class="show-permissions small">
                                    (
                                        <span class="show-text">{{ trans('labels.general.show') }}</span>
                                        <span class="hide-text hidden">{{ trans('labels.general.hide') }}</span>
                                        {{ trans('labels.backend.access.users.permissions') }}
                                    )
                                </a>
                                <br/>
                                <div class="permission-list hidden" data-role="role_{{ $role->id }}">
                                    @if ($role->all)
                                        {{ trans('labels.backend.access.users.all_permissions') }}<br/><br/>
                                    @else
                                        @if (count($role->permissions) > 0)
                                            <blockquote class="small">{{--
                                        --}}@foreach ($role->permissions as $perm){{--
                                            --}}{{$perm->display_name}}<br/>
                                                @endforeach
                                            </blockquote>
                                        @else
                                            {{ trans('labels.backend.access.users.no_permissions') }}<br/><br/>
                                        @endif
                                    @endif
                                </div><!--permission list-->
                            @endforeach
                        @else
                            {{ trans('labels.backend.access.users.no_roles') }}
                        @endif
                    </div><!--col-lg-3-->
                </div><!--form control-->
            </div><!-- /.box-body -->
        </div><!--box-->

        <div class="box box-info">
            <div class="box-body">
                <div class="pull-left">
                    {{ link_to_route('admin.access.user.index', trans('buttons.general.cancel'), [], ['class' => 'btn btn-danger btn-xs']) }}
                </div><!--pull-left-->

                <div class="pull-right">
                    {{ Form::submit(trans('buttons.general.crud.create'), ['class' => 'btn btn-success btn-xs']) }}
                </div><!--pull-right-->

                <div class="clearfix"></div>
            </div><!-- /.box-body -->
        </div><!--box-->

    {{ Form::close() }}
@stop

@section('after-scripts-end')
    {{ Html::script('js/backend/access/users/script.js') }}
@stop

resources/views/backend/access/index.blade.php
@extends ('backend.layouts.master')

@section ('title', trans('labels.backend.access.users.management'))

@section('after-styles-end')
    {{ Html::style("css/backend/plugin/datatables/dataTables.bootstrap.min.css") }}
@stop

@section('page-header')
    <h1>
        {{ trans('labels.backend.access.users.management') }}
        <small>{{ trans('labels.backend.access.users.active') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('labels.backend.access.users.active') }}</h3>

            <div class="box-tools pull-right">
                @include('backend.access.includes.partials.header-buttons')
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->

        <div class="box-body">
            <div class="table-responsive">
                <table id="users-table" class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>{{ trans('labels.backend.access.users.table.id') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.name') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.email') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.confirmed') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.roles') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.created') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.last_updated') }}</th>
                            <th>{{ trans('labels.general.actions') }}</th>
                        </tr>
                    </thead>
                </table>
            </div><!--table-responsive-->
        </div><!-- /.box-body -->
    </div><!--box-->

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('history.backend.recent_history') }}</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
            {!! history()->renderType('User') !!}
        </div><!-- /.box-body -->
    </div><!--box box-success-->
@stop

@section('after-scripts-end')
    {{ Html::script("js/backend/plugin/datatables/jquery.dataTables.min.js") }}
    {{ Html::script("js/backend/plugin/datatables/dataTables.bootstrap.min.js") }}

    <script>
        $(function() {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route("admin.access.user.get") }}',
                    type: 'get',
                    data: {status: 1, trashed: false}
                },
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'confirmed', name: 'confirmed'},
                    {data: 'roles', name: 'roles'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'updated_at', name: 'updated_at'},
                    {data: 'actions', name: 'actions'}
                ],
                order: [[0, "asc"]],
                searchDelay: 500
            });
        });
    </script>
@stop